'use client'
import CategoryList from "../../components/category/category_list";
import * as React from "react";
import styles from './page.module.css'
import {Container} from "@mui/material";
import {useState, useEffect} from "react";
import {BASE_URL} from "../Constants";
import CreateWithModalButton from "../../components/CreateWithModalButton";
import CreateForm from "../../components/category/CreateForm";

export const metadata = {
    title: 'Categories',
    description: 'Generated by create next app',
};

export default function Category() {
    const [categories, setCategories] = useState([]);
    const [isLoading, setLoading] = useState(false);
    const fetchCats = async () => {
        try {
            setLoading(true);
            const headers = {
                'content-type': 'application/json',
                // 'Authorization': `Bearer ${HYGRAPH_PERMANENTAUTH_TOKEN}`
            };
            const requestBody = {
                query: ` {
            categories{
                    _id
                    name
                    image
                }
            }`,
            };
            const options = {
                method: 'POST',
                headers,
                body: JSON.stringify(requestBody)
            };
            const response = await (await fetch(BASE_URL, options)).json();
            return response;
        }catch (err){
            console.log(err)
        }finally {
            setLoading(false);
        }
    };

    useEffect( () => {
        fetchCats().then(response=>{
            setCategories(response.data.categories);
        });
    }, []);

    if (isLoading) return <p>Loading...</p>;
    if (categories.length === 0) return <p>No profile data</p>;

    return (

        <main className={styles.main}>
            <Container>
                <div className="p-1 sm:p-8">
                    <CreateWithModalButton styles={{width:"50%",margin:"1rem",padding:"1rem"}} show={true} title="اضافة تصنيف">
                        <CreateForm edit={true} create={true} />
                    </CreateWithModalButton>
                </div>
                <CategoryList items={categories}/>
            </Container>
        </main>

    );
}