'use client'
import styles from '../page.module.css'
import {Container} from "@mui/material";
export const metadata = {
    title: 'Categories',
    description: 'Generated by create next app',
}
export default function New() {
    return (

        <main className={styles.main}>
            <Container>

            </Container>
        </main>

    );
}