'use client';
import './globals.css'
import {Container} from "@mui/material";
import styles from './page.module.css'
import * as React from "react";
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
    <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" />
                <link href="https://fonts.googleapis.com/css2?family=Noto+Kufi+Arabic:wght@300&display=swap" rel="stylesheet" />
    </head>
      <body className={`${styles.bodyRtl} bg-stone-300	`}>
      <div className={`bg-yellow-500 p-3 ${styles["header-curved"]}`}>
          <h1 className="text-center text-2xl font-bold">المزارع </h1>
      </div>
        <Container className="mt-10  lg:pl-72 lg:pr-72 sm:pl-0 sm:pr-0">
          {children}
        </Container>
      </body>
    </html>
  )
}
