
'use client'
import CreateWithModalButton from "../../../../components/CreateWithModalButton";
import PostList from "../../../../components/post/category_list";
import * as React from "react";
import styles from '../../page.module.css'
import {Container} from "@mui/material";
import {useState, useEffect} from "react";
import {BASE_URL} from "../../../Constants";
import CreateForm from "../../../../components/post/CreateForm";



export const metadata = {
    title: 'Posts',
    description: 'Generated by create next app',
};

export default function Posts({params}) {
    const categoryId=params.categoryId;
    const [posts, setPosts] = useState([]);
    const [isLoading, setLoading] = useState(false);
    const fetchCats = async () => {
        try {
            setLoading(true);
            const headers = {
                'content-type': 'application/json',
                // 'Authorization': `Bearer ${HYGRAPH_PERMANENTAUTH_TOKEN}`
            };
            const requestBody = {
                query: '{ postsByCategory(category_id:"'+categoryId+'"){ _id title description attachment }}',
            };
            const options = {
                method: 'POST',
                headers,
                body: JSON.stringify(requestBody)
            };
            const response = await (await fetch(BASE_URL, options)).json();
            return response;
        } catch (err) {
            console.log(err)
        } finally {
            setLoading(false);
        }
    };

    useEffect(() => {
        fetchCats().then(response => {
            setPosts(response.data.postsByCategory);
        });
    }, []);

    if (isLoading) return <p>Loading...</p>;
    if (posts.length === 0) return <p>No profile data</p>;

    return (

        <main className={styles.main}>
            <Container>
                <div className="p-1 sm:p-8">
                    <CreateWithModalButton styles={{width:"50%",margin:"1rem",padding:"1rem"}} show={true} title="اضافة مقاله">
                        <CreateForm cat_id={categoryId} edit={true}  create={true} />
                    </CreateWithModalButton>
                </div>
                <PostList items={posts} category={categoryId}/>
            </Container>
        </main>

    );
}